-- ============================================================================
-- 006 — Room directory (S24.2)
--
-- SOURCE:    https://maps.unimelb.edu.au/parkville  — the University's own
--            interactive campus map. Its data is served by MazeMap, the
--            platform UoM publishes that map on; the rows below were read from
--            the same public endpoint the map itself calls:
--              https://api.mazemap.com/api/pois/?buildingid=<id>&srid=4326
--            (Parkville is campusId 200). Individual rooms are also addressable
--            as public pages, e.g.
--              https://maps.unimelb.edu.au/point?115=&3=&305=&identifier=PAR
--            which is Redmond Barry 305, one of the rows below.
-- RETRIEVED: 2026-08-15
--
-- UoM's accessibility guide points students at this same map as the place to
-- look up campus facilities ("You can locate accessible toilets on Campus
-- Maps"), so it is the University speaking about its own buildings rather than
-- a third party describing them.
--
-- Requires migration 019 to have run first. Without it, has_power,
-- is_bookable and is_accessible are NOT NULL DEFAULT FALSE, and inserting these
-- rows would silently assert 2,670 facts nobody has checked.
--
-- ── What is in a row, and what is not ──
--
--   code         the room identifier UoM's own space register uses. Taken from
--                the map's `identifier` field, which is "PAR;<building>;<floor>;
--                <room>" — so Redmond Barry's Lyle Theatre is code '101',
--                which is what a timetable says and what is on the door.
--                Where a POI carried no identifier, the code was taken from the
--                map's own alternate-name list, but only when that name matched
--                a room-code shape; otherwise the room was dropped.
--   name         the map's display title, when it differs from the code.
--                "LYLE THEATRE (101)", "Dulcie Hollyock Room".
--   floor_level  derived from the map's floor label: G -> 0, L<n> -> n,
--                B/B1 -> -1, B2 -> -2. This is the only interpretation applied
--                to the source, and it is one-to-one.
--   room_type    a translation of UoM's own space category into this schema's
--                seven-value enum. The full mapping, so it can be audited:
--                  Lecture Theatre             -> lecture
--                  Flexible Learning Space     -> tutorial
--                  Collaborative Learning Space-> tutorial
--                  Specialist Teaching         -> tutorial
--                  Laboratory Space            -> lab
--                  Informal Learning Space     -> study
--                  Study Space                 -> study
--                  Study Sanctuary             -> study
--                  Focus Room                  -> study
--                  Library Space               -> library
--                  Meeting Room                -> meeting
--                Every other category the map carries — Workstation, Toilet,
--                Circulation, Stairs, Lift, Kitchen, Retail, Office and the
--                rest — is deliberately not seeded. This is a directory of
--                rooms a student might be sent to, not a floor plan.
--   capacity     NOT seeded. The map exposes a peopleCapacity field and it is
--                empty for every Parkville room read on 2026-08-15. UoM does
--                publish capacities, in Room Search
--                (https://learningspaces.unimelb.edu.au/room-search) — a POST
--                form sitting behind bot protection which could not be read
--                programmatically. That remains an open data item.
--   has_power / is_bookable / is_accessible
--                NOT seeded — left NULL by migration 019. No source.
--
-- ── Caveats, recorded rather than dropped ──
--
-- 1. Engineering Building 1 gets no rooms. Seed 001 calls it "Engineering
--    Building 1 (Block B)", which is not a name UoM publishes: the campus map
--    and Room Search both list INFRASTRUCTURE ENGINEERING (BLOCK B/C/D)
--    (buildings 175/174/176) and several other engineering buildings, and the
--    seeded centroid does not land on any of them (its nearest neighbour is the
--    Sidney Myer Asia Centre, ~30 m away). Rather than pick one and be
--    confidently wrong about where a student's class is, it is left empty.
--    RoomList renders nothing for a building with no rooms, which is the honest
--    output.
--
-- 2. Chemistry Building is seeded from UoM Building 153 only. Seed 003 defines
--    it as "Building 153, Masson Rd"; the campus map and Room Search both call
--    153 the CHEMISTRY BUILDING (WEST WING) and carry a separate East Wing
--    (154) that this project does not model. Exactly 1 East Wing space would
--    have qualified as a room under the mapping above, and it is absent. It is
--    not missing data — it belongs to a building Pulse has not seeded.
--
-- 3. 36 rooms were dropped because their floor label does not map one-to-one
--    onto an integer level: 30 on the FBE Building's "UG" (upper ground) and 6
--    on "GM" (ground mezzanine) floors. Guessing whether UG is 0 or 1 in a
--    building that also has a "G" would put a student on the wrong floor.
--
-- 4. Building identity was resolved by name against UoM's own two building
--    registers — the campus map and Room Search
--    (https://learningspaces.unimelb.edu.au/room-search, whose building list
--    gives the number for every teaching building) — not by coordinate. Several
--    seeded centroids are tens to hundreds of metres out, so matching on
--    position would have attached rooms to the wrong building.
--
--    One identification is worth spelling out because neither register carries
--    the name this project uses. Pulse's "Doug McDonell Building (ICT)" is UoM
--    Building 168, which both registers list only as "BUILDING 168". The link
--    is the University's own architectural drawings, catalogued in its
--    institutional repository as "Building 168, Doug Mcdonell Building: Level 5
--    Finishes Plan" — https://digitised-collections.unimelb.edu.au/handle/11343/100141
--
-- 5. This is a snapshot. Rooms are renamed, repurposed and rebuilt; the
--    Baillieu is under redevelopment as this is written. The in-app "report an
--    error" path (S25) is the correction mechanism, and anyone re-verifying
--    should re-read the map and bump this seed.
--
-- Counts: 890 rooms across 17 of the 18 seeded buildings.
-- ============================================================================

INSERT INTO rooms (building_id, code, name, floor_level, room_type)
SELECT b.id, v.code, v.name, v.floor_level, v.room_type
FROM (VALUES
  -- Alan Gilbert Building — UoM Building 104 — 68 rooms
  ('alan-gilbert', 'CG05', NULL::text, 0, 'tutorial'),
  ('alan-gilbert', 'G01', 'Collaborative Learning Space', 0, 'tutorial'),
  ('alan-gilbert', 'G02', 'Collaborative Learning Space', 0, 'tutorial'),
  ('alan-gilbert', 'G03', 'Collaborative Learning Space', 0, 'tutorial'),
  ('alan-gilbert', 'G18', 'Flexible Learning Space', 0, 'lecture'),
  ('alan-gilbert', 'G19', NULL, 0, 'study'),
  ('alan-gilbert', 'G20', 'Flexible Learning Space', 0, 'lecture'),
  ('alan-gilbert', 'G21', NULL, 0, 'tutorial'),
  ('alan-gilbert', 'G26', 'Student Study Space G26', 0, 'study'),
  ('alan-gilbert', '101', 'Collaborative Learning Space', 1, 'tutorial'),
  ('alan-gilbert', '102', 'Collaborative Learning Space', 1, 'tutorial'),
  ('alan-gilbert', '103', 'Collaborative Learning Space', 1, 'tutorial'),
  ('alan-gilbert', '120', 'Lectorial Learning Space 120', 1, 'study'),
  ('alan-gilbert', '123', NULL, 1, 'tutorial'),
  ('alan-gilbert', '124', NULL, 1, 'tutorial'),
  ('alan-gilbert', '140', 'Project Room 04', 1, 'tutorial'),
  ('alan-gilbert', '141', 'Project Room 03', 1, 'tutorial'),
  ('alan-gilbert', '142', NULL, 1, 'study'),
  ('alan-gilbert', '143', 'Project Room 02', 1, 'tutorial'),
  ('alan-gilbert', '144', 'Project Room 01', 1, 'tutorial'),
  ('alan-gilbert', '145', NULL, 1, 'study'),
  ('alan-gilbert', '146', NULL, 1, 'study'),
  ('alan-gilbert', '147', 'Meeting Room 02', 1, 'meeting'),
  ('alan-gilbert', '148', 'Meeting Room 01', 1, 'meeting'),
  ('alan-gilbert', 'C102', NULL, 1, 'study'),
  ('alan-gilbert', 'C109', NULL, 1, 'study'),
  ('alan-gilbert', '233', 'Meeting Room', 2, 'meeting'),
  ('alan-gilbert', '234', 'Meeting Room', 2, 'meeting'),
  ('alan-gilbert', '235', NULL, 2, 'meeting'),
  ('alan-gilbert', '236', NULL, 2, 'meeting'),
  ('alan-gilbert', '300', 'Meeting Room 2', 3, 'meeting'),
  ('alan-gilbert', '304', NULL, 3, 'study'),
  ('alan-gilbert', '305', NULL, 3, 'study'),
  ('alan-gilbert', '306', 'Collaboration 02', 3, 'meeting'),
  ('alan-gilbert', '330', 'Meeting Room 3', 3, 'meeting'),
  ('alan-gilbert', '333', 'Meeting Room 1', 3, 'meeting'),
  ('alan-gilbert', '338', NULL, 3, 'meeting'),
  ('alan-gilbert', '353', 'Boardroom 02', 3, 'tutorial'),
  ('alan-gilbert', '354', 'Boardroom 01', 3, 'tutorial'),
  ('alan-gilbert', '420A', NULL, 4, 'study'),
  ('alan-gilbert', '420B', NULL, 4, 'study'),
  ('alan-gilbert', '420C', NULL, 4, 'study'),
  ('alan-gilbert', '421', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '422', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '423', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '441A', NULL, 4, 'study'),
  ('alan-gilbert', '481', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '482', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '483', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '484', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '485', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '487', 'Meeting Room', 4, 'meeting'),
  ('alan-gilbert', '511A', NULL, 5, 'study'),
  ('alan-gilbert', '511B', NULL, 5, 'study'),
  ('alan-gilbert', '511C', NULL, 5, 'study'),
  ('alan-gilbert', '521', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '522', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '523', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '531A', NULL, 5, 'study'),
  ('alan-gilbert', '561', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '564', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '565', 'Meeting Room', 5, 'meeting'),
  ('alan-gilbert', '622', 'Meeting Room', 6, 'meeting'),
  ('alan-gilbert', '632', 'Meeting Room', 6, 'meeting'),
  ('alan-gilbert', '703', NULL, 7, 'study'),
  ('alan-gilbert', '704', NULL, 7, 'meeting'),
  ('alan-gilbert', '711', 'Meeting Room 1', 7, 'meeting'),
  ('alan-gilbert', '727', NULL, 7, 'study'),
  -- Arts West — UoM Buildings 148A (North Wing) + 148B (West Wing) — 41 rooms
  ('arts-west', 'G04', NULL, 0, 'study'),
  ('arts-west', 'G14', 'Informal Learning Space (G14)', 0, 'study'),
  ('arts-west', 'G20', NULL, 0, 'meeting'),
  ('arts-west', '104', NULL, 1, 'study'),
  ('arts-west', '109', 'Meeting Room', 1, 'meeting'),
  ('arts-west', '153', 'FORUM THEATRE (153)', 1, 'lecture'),
  ('arts-west', '155', 'Collaborative Learning Space / Project Room', 1, 'tutorial'),
  ('arts-west', '161', NULL, 1, 'tutorial'),
  ('arts-west', '192', NULL, 1, 'study'),
  ('arts-west', '201', NULL, 2, 'study'),
  ('arts-west', '203', NULL, 2, 'study'),
  ('arts-west', '206', NULL, 2, 'study'),
  ('arts-west', '211', 'Collaborative Room III', 2, 'meeting'),
  ('arts-west', '212', 'Collaborative Room IV', 2, 'meeting'),
  ('arts-west', '251', NULL, 2, 'study'),
  ('arts-west', '253', 'Collaborative Learning Space / Project Room', 2, 'tutorial'),
  ('arts-west', '256', 'Flexible Learning Space', 2, 'lecture'),
  ('arts-west', '261', NULL, 2, 'tutorial'),
  ('arts-west', '263', NULL, 2, 'tutorial'),
  ('arts-west', '292', NULL, 2, 'study'),
  ('arts-west', '302', NULL, 3, 'study'),
  ('arts-west', '306', 'Collaborative Room I', 3, 'meeting'),
  ('arts-west', '307', 'Collaborative Room II', 3, 'meeting'),
  ('arts-west', '351', NULL, 3, 'study'),
  ('arts-west', '354', NULL, 3, 'tutorial'),
  ('arts-west', '355', 'Collaborative Learning Space / Project Room', 3, 'tutorial'),
  ('arts-west', '356', 'Flexible Learning Space', 3, 'lecture'),
  ('arts-west', '361', NULL, 3, 'tutorial'),
  ('arts-west', '401', 'Meeting Room', 4, 'meeting'),
  ('arts-west', '451', NULL, 4, 'study'),
  ('arts-west', '453', 'Flexible Learning Space', 4, 'lecture'),
  ('arts-west', '454', NULL, 4, 'tutorial'),
  ('arts-west', '455', 'Collaborative Learning Space / Project Room', 4, 'tutorial'),
  ('arts-west', '456', 'Flexible Learning Space', 4, 'lecture'),
  ('arts-west', '461', NULL, 4, 'tutorial'),
  ('arts-west', '493', NULL, 4, 'study'),
  ('arts-west', '502', 'Meeting Room', 5, 'meeting'),
  ('arts-west', '555', 'Collaborative Learning Space / Project Room', 5, 'tutorial'),
  ('arts-west', '561', NULL, 5, 'tutorial'),
  ('arts-west', '617', 'Meeting Room', 6, 'meeting'),
  ('arts-west', '691', 'Meeting Room Pod', 6, 'meeting'),
  -- Baillieu Library — UoM Building 177 — 117 rooms
  ('baillieu-library', 'B21', NULL, -1, 'library'),
  ('baillieu-library', 'B22', NULL, -1, 'library'),
  ('baillieu-library', 'B23', NULL, -1, 'library'),
  ('baillieu-library', 'B28', NULL, -1, 'library'),
  ('baillieu-library', 'G01', 'Dulcie Hollyock Room', 0, 'meeting'),
  ('baillieu-library', 'G11', NULL, 0, 'library'),
  ('baillieu-library', 'G12', NULL, 0, 'study'),
  ('baillieu-library', 'G12A', NULL, 0, 'study'),
  ('baillieu-library', 'G13', NULL, 0, 'study'),
  ('baillieu-library', 'G13A', NULL, 0, 'study'),
  ('baillieu-library', 'G14', NULL, 0, 'meeting'),
  ('baillieu-library', 'G15', NULL, 0, 'study'),
  ('baillieu-library', 'G16', NULL, 0, 'study'),
  ('baillieu-library', 'G17', NULL, 0, 'library'),
  ('baillieu-library', 'G18', NULL, 0, 'library'),
  ('baillieu-library', 'G20', NULL, 0, 'library'),
  ('baillieu-library', 'G21', NULL, 0, 'study'),
  ('baillieu-library', 'G22', NULL, 0, 'library'),
  ('baillieu-library', 'G23', NULL, 0, 'library'),
  ('baillieu-library', 'G24', NULL, 0, 'library'),
  ('baillieu-library', 'G25', NULL, 0, 'library'),
  ('baillieu-library', 'G26', NULL, 0, 'library'),
  ('baillieu-library', 'G27', NULL, 0, 'library'),
  ('baillieu-library', 'G29', NULL, 0, 'library'),
  ('baillieu-library', 'G30', NULL, 0, 'library'),
  ('baillieu-library', 'G31', NULL, 0, 'library'),
  ('baillieu-library', 'G32', NULL, 0, 'library'),
  ('baillieu-library', 'G33', NULL, 0, 'library'),
  ('baillieu-library', 'G34', NULL, 0, 'library'),
  ('baillieu-library', 'G35', NULL, 0, 'study'),
  ('baillieu-library', 'G35A', NULL, 0, 'study'),
  ('baillieu-library', 'G35B', NULL, 0, 'study'),
  ('baillieu-library', 'G38', NULL, 0, 'library'),
  ('baillieu-library', 'G39', NULL, 0, 'study'),
  ('baillieu-library', 'G39B', NULL, 0, 'library'),
  ('baillieu-library', 'G40', NULL, 0, 'study'),
  ('baillieu-library', 'G42', NULL, 0, 'library'),
  ('baillieu-library', 'G60', NULL, 0, 'study'),
  ('baillieu-library', 'G63', NULL, 0, 'study'),
  ('baillieu-library', 'G63A', NULL, 0, 'study'),
  ('baillieu-library', 'G63B', NULL, 0, 'study'),
  ('baillieu-library', 'G64', NULL, 0, 'study'),
  ('baillieu-library', 'G64A', NULL, 0, 'study'),
  ('baillieu-library', 'G65A', NULL, 0, 'library'),
  ('baillieu-library', 'G65B', NULL, 0, 'library'),
  ('baillieu-library', 'G65C', NULL, 0, 'library'),
  ('baillieu-library', 'G65D', NULL, 0, 'library'),
  ('baillieu-library', 'G65E', NULL, 0, 'library'),
  ('baillieu-library', 'G65F', NULL, 0, 'library'),
  ('baillieu-library', 'G65G', NULL, 0, 'library'),
  ('baillieu-library', 'G65H', NULL, 0, 'library'),
  ('baillieu-library', 'G66', NULL, 0, 'library'),
  ('baillieu-library', '101', NULL, 1, 'library'),
  ('baillieu-library', '103', 'Leigh Scott Room', 1, 'meeting'),
  ('baillieu-library', '107', NULL, 1, 'library'),
  ('baillieu-library', '109', NULL, 1, 'library'),
  ('baillieu-library', '110', NULL, 1, 'library'),
  ('baillieu-library', '111', NULL, 1, 'library'),
  ('baillieu-library', '112', NULL, 1, 'library'),
  ('baillieu-library', '121', NULL, 1, 'library'),
  ('baillieu-library', '124', NULL, 1, 'meeting'),
  ('baillieu-library', '125', NULL, 1, 'study'),
  ('baillieu-library', '128', NULL, 1, 'library'),
  ('baillieu-library', '129', 'L1 Recording Space 129', 1, 'library'),
  ('baillieu-library', '130', 'L1 Recording Space 130', 1, 'library'),
  ('baillieu-library', '140A', NULL, 1, 'study'),
  ('baillieu-library', '141', 'L1 Recording Pod 141', 1, 'library'),
  ('baillieu-library', '142', 'L1 Recording Pod 142', 1, 'library'),
  ('baillieu-library', '205', NULL, 2, 'study'),
  ('baillieu-library', '206', NULL, 2, 'study'),
  ('baillieu-library', '207', NULL, 2, 'study'),
  ('baillieu-library', '207A', NULL, 2, 'library'),
  ('baillieu-library', '208', NULL, 2, 'study'),
  ('baillieu-library', '208A', NULL, 2, 'library'),
  ('baillieu-library', '208B', NULL, 2, 'study'),
  ('baillieu-library', '208C', NULL, 2, 'library'),
  ('baillieu-library', '209', NULL, 2, 'study'),
  ('baillieu-library', '211', NULL, 2, 'study'),
  ('baillieu-library', '212', NULL, 2, 'library'),
  ('baillieu-library', '213', NULL, 2, 'library'),
  ('baillieu-library', '214', NULL, 2, 'library'),
  ('baillieu-library', '215', NULL, 2, 'study'),
  ('baillieu-library', '221', NULL, 2, 'study'),
  ('baillieu-library', '222', NULL, 2, 'library'),
  ('baillieu-library', '222A', NULL, 2, 'study'),
  ('baillieu-library', '223', NULL, 2, 'library'),
  ('baillieu-library', '224', NULL, 2, 'library'),
  ('baillieu-library', '225', NULL, 2, 'study'),
  ('baillieu-library', '228', NULL, 2, 'library'),
  ('baillieu-library', '301', NULL, 3, 'library'),
  ('baillieu-library', '302', NULL, 3, 'study'),
  ('baillieu-library', '303', NULL, 3, 'library'),
  ('baillieu-library', '303A', NULL, 3, 'library'),
  ('baillieu-library', '303B', NULL, 3, 'study'),
  ('baillieu-library', '304', NULL, 3, 'library'),
  ('baillieu-library', '304A', NULL, 3, 'study'),
  ('baillieu-library', '304B', NULL, 3, 'study'),
  ('baillieu-library', '308', NULL, 3, 'library'),
  ('baillieu-library', '316', NULL, 3, 'library'),
  ('baillieu-library', '317', NULL, 3, 'library'),
  ('baillieu-library', '318', NULL, 3, 'library'),
  ('baillieu-library', '318A', NULL, 3, 'library'),
  ('baillieu-library', '318B', NULL, 3, 'study'),
  ('baillieu-library', '318C', NULL, 3, 'library'),
  ('baillieu-library', '318G', NULL, 3, 'library'),
  ('baillieu-library', '319', NULL, 3, 'study'),
  ('baillieu-library', '321', NULL, 3, 'library'),
  ('baillieu-library', '401', NULL, 4, 'study'),
  ('baillieu-library', '403', 'Meeting', 4, 'meeting'),
  ('baillieu-library', '405', NULL, 4, 'study'),
  ('baillieu-library', '420A', 'Meeting Pod', 4, 'meeting'),
  ('baillieu-library', '421', NULL, 4, 'study'),
  ('baillieu-library', '422', NULL, 4, 'study'),
  ('baillieu-library', '423', 'Conf/Meeting', 4, 'meeting'),
  ('baillieu-library', '424', 'Conf/Meeting', 4, 'meeting'),
  ('baillieu-library', '425', 'Meeting', 4, 'meeting'),
  ('baillieu-library', '431', NULL, 4, 'study'),
  -- Chemistry Building — UoM Building 153 (West Wing) only; see header — 10 rooms
  ('chemistry-building', '137', NULL, 1, 'study'),
  ('chemistry-building', '158', NULL, 1, 'tutorial'),
  ('chemistry-building', '160', NULL, 1, 'study'),
  ('chemistry-building', '161', NULL, 1, 'study'),
  ('chemistry-building', '162', NULL, 1, 'study'),
  ('chemistry-building', '169', 'Collaborative Learning Space', 1, 'tutorial'),
  ('chemistry-building', '175', NULL, 1, 'meeting'),
  ('chemistry-building', '178', 'Cuming Theatre', 1, 'lecture'),
  ('chemistry-building', '273', NULL, 2, 'tutorial'),
  ('chemistry-building', '371', 'Senior Theatre', 3, 'meeting'),
  -- David Caro Building — UoM Building 192 — 32 rooms
  ('david-caro', '174', 'Laby IDEAS Centre', 1, 'tutorial'),
  ('david-caro', '175', 'PBL Space', 1, 'tutorial'),
  ('david-caro', '175A', 'PBL Space', 1, 'tutorial'),
  ('david-caro', '176', 'PBL Space', 1, 'tutorial'),
  ('david-caro', '177', 'PBL Space', 1, 'tutorial'),
  ('david-caro', '178', 'PBL Space', 1, 'tutorial'),
  ('david-caro', '185A', NULL, 1, 'lab'),
  ('david-caro', '185B', NULL, 1, 'lab'),
  ('david-caro', '189', NULL, 1, 'lab'),
  ('david-caro', '201', NULL, 2, 'tutorial'),
  ('david-caro', '202', NULL, 2, 'tutorial'),
  ('david-caro', '203', NULL, 2, 'tutorial'),
  ('david-caro', '204', NULL, 2, 'tutorial'),
  ('david-caro', '205', NULL, 2, 'tutorial'),
  ('david-caro', '207', NULL, 2, 'tutorial'),
  ('david-caro', '210', NULL, 2, 'tutorial'),
  ('david-caro', '211', NULL, 2, 'tutorial'),
  ('david-caro', '260', NULL, 2, 'tutorial'),
  ('david-caro', '279', 'Meeting Room', 2, 'meeting'),
  ('david-caro', '293', NULL, 2, 'study'),
  ('david-caro', 'L105', 'HERCUS THEATRE (L105)', 2, 'lecture'),
  ('david-caro', 'L108', 'LABY THEATRE (L108)', 2, 'lecture'),
  ('david-caro', '365', 'CAASTRO Video Conference Rm', 3, 'meeting'),
  ('david-caro', 'P301B', NULL, 3, 'lab'),
  ('david-caro', 'P304B', NULL, 3, 'lab'),
  ('david-caro', 'P305B', NULL, 3, 'lab'),
  ('david-caro', 'P308B', NULL, 3, 'lab'),
  ('david-caro', '442', 'Meeting Room', 4, 'meeting'),
  ('david-caro', '660', 'Geoff Opat Seminar Room', 6, 'meeting'),
  ('david-caro', '662', 'Research Reading Room', 6, 'meeting'),
  ('david-caro', '754', NULL, 7, 'meeting'),
  ('david-caro', '760', NULL, 7, 'meeting'),
  -- Eastern Resource Centre — UoM Building 171 — 87 rooms
  ('erc-library', 'B02', NULL, -1, 'library'),
  ('erc-library', 'B03', NULL, -1, 'study'),
  ('erc-library', 'B04', NULL, -1, 'library'),
  ('erc-library', 'B05', NULL, -1, 'library'),
  ('erc-library', 'B06', NULL, -1, 'library'),
  ('erc-library', 'B07', NULL, -1, 'library'),
  ('erc-library', 'B08', NULL, -1, 'library'),
  ('erc-library', 'B09', NULL, -1, 'library'),
  ('erc-library', 'B11', NULL, -1, 'study'),
  ('erc-library', 'B12', NULL, -1, 'study'),
  ('erc-library', 'B13', 'AV Recording Room B13', -1, 'library'),
  ('erc-library', 'CG01', NULL, 0, 'study'),
  ('erc-library', 'G02', NULL, 0, 'study'),
  ('erc-library', 'G03', NULL, 0, 'study'),
  ('erc-library', 'G04', NULL, 0, 'study'),
  ('erc-library', 'G05', NULL, 0, 'study'),
  ('erc-library', 'G06', NULL, 0, 'study'),
  ('erc-library', 'G07', NULL, 0, 'study'),
  ('erc-library', 'G08', NULL, 0, 'study'),
  ('erc-library', '101', NULL, 1, 'study'),
  ('erc-library', '102', NULL, 1, 'study'),
  ('erc-library', '103A', NULL, 1, 'study'),
  ('erc-library', '103B', NULL, 1, 'study'),
  ('erc-library', '104', NULL, 1, 'study'),
  ('erc-library', '105', NULL, 1, 'study'),
  ('erc-library', '107', NULL, 1, 'study'),
  ('erc-library', '111', NULL, 1, 'library'),
  ('erc-library', '112', NULL, 1, 'library'),
  ('erc-library', '113', NULL, 1, 'study'),
  ('erc-library', '114', NULL, 1, 'study'),
  ('erc-library', '115', NULL, 1, 'study'),
  ('erc-library', '116', NULL, 1, 'study'),
  ('erc-library', '117', NULL, 1, 'study'),
  ('erc-library', '117B', NULL, 1, 'study'),
  ('erc-library', '118', NULL, 1, 'study'),
  ('erc-library', '121', NULL, 1, 'study'),
  ('erc-library', '121A', NULL, 1, 'study'),
  ('erc-library', '122', NULL, 1, 'library'),
  ('erc-library', '123', NULL, 1, 'library'),
  ('erc-library', '124', NULL, 1, 'library'),
  ('erc-library', '201', NULL, 2, 'study'),
  ('erc-library', '201A', NULL, 2, 'library'),
  ('erc-library', '202', NULL, 2, 'library'),
  ('erc-library', '202A', NULL, 2, 'study'),
  ('erc-library', '203', NULL, 2, 'study'),
  ('erc-library', '204', NULL, 2, 'library'),
  ('erc-library', '205', NULL, 2, 'library'),
  ('erc-library', '205A', NULL, 2, 'study'),
  ('erc-library', '206', NULL, 2, 'library'),
  ('erc-library', '207', NULL, 2, 'library'),
  ('erc-library', '209A', NULL, 2, 'study'),
  ('erc-library', '209B', NULL, 2, 'study'),
  ('erc-library', '211', NULL, 2, 'library'),
  ('erc-library', '212', NULL, 2, 'library'),
  ('erc-library', '213', NULL, 2, 'study'),
  ('erc-library', '213A', NULL, 2, 'study'),
  ('erc-library', '214', NULL, 2, 'library'),
  ('erc-library', '215', NULL, 2, 'study'),
  ('erc-library', '215A', NULL, 2, 'library'),
  ('erc-library', '216', NULL, 2, 'study'),
  ('erc-library', '217', NULL, 2, 'library'),
  ('erc-library', '217B', NULL, 2, 'study'),
  ('erc-library', '218', NULL, 2, 'study'),
  ('erc-library', '221', NULL, 2, 'study'),
  ('erc-library', '221A', NULL, 2, 'library'),
  ('erc-library', '222', NULL, 2, 'study'),
  ('erc-library', '222A', NULL, 2, 'study'),
  ('erc-library', '223', NULL, 2, 'study'),
  ('erc-library', '223A', NULL, 2, 'library'),
  ('erc-library', '224', NULL, 2, 'study'),
  ('erc-library', '301', NULL, 3, 'library'),
  ('erc-library', '301A', NULL, 3, 'library'),
  ('erc-library', '302', NULL, 3, 'study'),
  ('erc-library', '302A', NULL, 3, 'library'),
  ('erc-library', '303', NULL, 3, 'study'),
  ('erc-library', '305', NULL, 3, 'study'),
  ('erc-library', '306', NULL, 3, 'library'),
  ('erc-library', '311', NULL, 3, 'library'),
  ('erc-library', '312', NULL, 3, 'library'),
  ('erc-library', '313', NULL, 3, 'study'),
  ('erc-library', '313A', NULL, 3, 'study'),
  ('erc-library', '314', NULL, 3, 'study'),
  ('erc-library', '315', NULL, 3, 'study'),
  ('erc-library', '316', NULL, 3, 'study'),
  ('erc-library', '321', NULL, 3, 'study'),
  ('erc-library', '322', NULL, 3, 'study'),
  ('erc-library', '323', NULL, 3, 'study'),
  -- FBE Building — UoM Building 105 — 76 rooms
  ('fbe-building', 'G06', 'Prest Theatre', 0, 'lecture'),
  ('fbe-building', 'G24', 'Giblin Eunson Library (G24)', 0, 'library'),
  ('fbe-building', 'G24A', NULL, 0, 'library'),
  ('fbe-building', 'G24C', NULL, 0, 'library'),
  ('fbe-building', 'G24D', NULL, 0, 'study'),
  ('fbe-building', 'G24E', NULL, 0, 'study'),
  ('fbe-building', 'G24F', NULL, 0, 'study'),
  ('fbe-building', 'G24G', NULL, 0, 'study'),
  ('fbe-building', 'G26', NULL, 0, 'library'),
  ('fbe-building', 'G27', 'Recording Pod', 0, 'library'),
  ('fbe-building', 'G28', 'Recording Booth', 0, 'library'),
  ('fbe-building', 'G29', NULL, 0, 'library'),
  ('fbe-building', 'G30', NULL, 0, 'library'),
  ('fbe-building', 'G31', NULL, 0, 'library'),
  ('fbe-building', 'G33', NULL, 0, 'library'),
  ('fbe-building', 'G34', NULL, 0, 'library'),
  ('fbe-building', 'G35', NULL, 0, 'library'),
  ('fbe-building', 'G35A', NULL, 0, 'study'),
  ('fbe-building', 'G36', NULL, 0, 'library'),
  ('fbe-building', 'G38', NULL, 0, 'study'),
  ('fbe-building', '101', NULL, 1, 'study'),
  ('fbe-building', '107', NULL, 1, 'study'),
  ('fbe-building', '107A', NULL, 1, 'study'),
  ('fbe-building', '107B', NULL, 1, 'study'),
  ('fbe-building', '107C', NULL, 1, 'study'),
  ('fbe-building', '108', NULL, 1, 'library'),
  ('fbe-building', '111', 'Staff Meeting Room', 1, 'meeting'),
  ('fbe-building', '120', NULL, 1, 'library'),
  ('fbe-building', '120A', NULL, 1, 'study'),
  ('fbe-building', '121', NULL, 1, 'library'),
  ('fbe-building', '122', NULL, 1, 'library'),
  ('fbe-building', '123', NULL, 1, 'library'),
  ('fbe-building', '124', NULL, 1, 'study'),
  ('fbe-building', '125', NULL, 1, 'library'),
  ('fbe-building', '126', NULL, 1, 'study'),
  ('fbe-building', '127', NULL, 1, 'library'),
  ('fbe-building', '127A', NULL, 1, 'study'),
  ('fbe-building', '127B', NULL, 1, 'study'),
  ('fbe-building', '205', 'Theatre 3', 2, 'lecture'),
  ('fbe-building', '209', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '210', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '211', 'Theatre 2', 2, 'lecture'),
  ('fbe-building', '212', 'Collaborative Learning Space', 2, 'tutorial'),
  ('fbe-building', '213', 'Collaborative Learning Space', 2, 'tutorial'),
  ('fbe-building', '214', 'Collaborative Learning Space', 2, 'tutorial'),
  ('fbe-building', '215', NULL, 2, 'study'),
  ('fbe-building', '219', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '220', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '221', 'Theatre 4', 2, 'lecture'),
  ('fbe-building', '222', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '223', 'Breakout Space', 2, 'tutorial'),
  ('fbe-building', '224', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '225', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '226', 'PBL Space', 2, 'tutorial'),
  ('fbe-building', '227', NULL, 2, 'study'),
  ('fbe-building', '304', NULL, 3, 'meeting'),
  ('fbe-building', '308', NULL, 3, 'meeting'),
  ('fbe-building', '315', NULL, 3, 'tutorial'),
  ('fbe-building', '365', NULL, 3, 'meeting'),
  ('fbe-building', '404', 'Meeting Room', 4, 'meeting'),
  ('fbe-building', '437', NULL, 4, 'meeting'),
  ('fbe-building', '454', NULL, 4, 'meeting'),
  ('fbe-building', '455', NULL, 4, 'meeting'),
  ('fbe-building', '456', NULL, 4, 'meeting'),
  ('fbe-building', '475', NULL, 4, 'meeting'),
  ('fbe-building', '476', NULL, 4, 'meeting'),
  ('fbe-building', '508', 'Downing Boardroom', 5, 'meeting'),
  ('fbe-building', '509', NULL, 5, 'meeting'),
  ('fbe-building', '553', NULL, 5, 'meeting'),
  ('fbe-building', '557', NULL, 5, 'meeting'),
  ('fbe-building', '558C', NULL, 5, 'meeting'),
  ('fbe-building', '605', NULL, 6, 'tutorial'),
  ('fbe-building', '606', NULL, 6, 'tutorial'),
  ('fbe-building', '607', 'Meeting Room', 6, 'meeting'),
  ('fbe-building', '617', NULL, 6, 'meeting'),
  ('fbe-building', '630', 'Meeting Room', 6, 'meeting'),
  -- Doug McDonell Building (ICT) — UoM Building 168 — 44 rooms
  ('ict-building', '201', 'Meeting Room', 2, 'meeting'),
  ('ict-building', '216', 'Meeting Room', 2, 'meeting'),
  ('ict-building', '231', NULL, 2, 'study'),
  ('ict-building', '232', NULL, 2, 'study'),
  ('ict-building', '233', NULL, 2, 'study'),
  ('ict-building', '234', NULL, 2, 'study'),
  ('ict-building', '235', NULL, 2, 'study'),
  ('ict-building', '331', NULL, 3, 'study'),
  ('ict-building', '332', NULL, 3, 'study'),
  ('ict-building', '333', NULL, 3, 'study'),
  ('ict-building', '334', NULL, 3, 'study'),
  ('ict-building', '335', NULL, 3, 'study'),
  ('ict-building', '401', 'Radio Fodder', 4, 'library'),
  ('ict-building', '402', 'Radio Fodder', 4, 'library'),
  ('ict-building', '412', 'Media', 4, 'library'),
  ('ict-building', '416', NULL, 4, 'tutorial'),
  ('ict-building', '501', 'Atlantic Fellows for Social Equity (AFSE) Welcome Space 501', 5, 'meeting'),
  ('ict-building', '504', 'Atlantic Fellows for Social Equity (AFSE) Elder’s Lounge 504', 5, 'meeting'),
  ('ict-building', '508', 'Atlantic Fellows for Social Equity (AFSE) Meeting Room 508', 5, 'meeting'),
  ('ict-building', '509', 'Atlantic Fellows for Social Equity (AFSE) Meeting Room 509', 5, 'meeting'),
  ('ict-building', '513', 'Atlantic Fellows for Social Equity (AFSE) Meeting Room 513', 5, 'meeting'),
  ('ict-building', '602', 'Meeting Room', 6, 'meeting'),
  ('ict-building', '607', NULL, 6, 'study'),
  ('ict-building', '701', 'Meeting Room', 7, 'meeting'),
  ('ict-building', '702', 'Meeting Room', 7, 'meeting'),
  ('ict-building', '703', 'Consult Room', 7, 'meeting'),
  ('ict-building', '708', NULL, 7, 'study'),
  ('ict-building', '709', NULL, 7, 'study'),
  ('ict-building', '801', 'Quoll Corner (801)', 8, 'meeting'),
  ('ict-building', '802', 'Bilby Room (802)', 8, 'meeting'),
  ('ict-building', '803', 'Numbat Pod (803)', 8, 'study'),
  ('ict-building', '806', 'Ibis Pod (806)', 8, 'study'),
  ('ict-building', '807', 'Rosella Pod (807)', 8, 'study'),
  ('ict-building', '808', 'Kookaburra Pod (808)', 8, 'study'),
  ('ict-building', '815', 'Wombat Room (815)', 8, 'meeting'),
  ('ict-building', '816', 'Koala Room (816)', 8, 'meeting'),
  ('ict-building', '817', 'Possum Pod (817)', 8, 'study'),
  ('ict-building', '818', 'Platypus Pod (818)', 8, 'study'),
  ('ict-building', '819', 'Puggle Pod (819)', 8, 'study'),
  ('ict-building', '901', NULL, 9, 'study'),
  ('ict-building', '906', 'Meeting', 9, 'meeting'),
  ('ict-building', '910', 'Training Room 01 (910)', 9, 'meeting'),
  ('ict-building', '911', 'Training Room 02 (911)', 9, 'meeting'),
  ('ict-building', '917', NULL, 9, 'study'),
  -- John Medley Building — UoM Building 191 — 19 rooms
  ('john-medley', 'EG62', NULL, 0, 'tutorial'),
  ('john-medley', 'EG63', NULL, 0, 'tutorial'),
  ('john-medley', 'EG66', NULL, 0, 'tutorial'),
  ('john-medley', 'WG03', 'Collaborative Learning Space', 0, 'tutorial'),
  ('john-medley', 'WG05', 'Collaborative Learning Space', 0, 'tutorial'),
  ('john-medley', 'W131', 'Meeting Room', 1, 'meeting'),
  ('john-medley', 'E261', 'Meeting Room', 2, 'meeting'),
  ('john-medley', 'W201', NULL, 2, 'tutorial'),
  ('john-medley', 'E361', NULL, 3, 'library'),
  ('john-medley', 'W301A', NULL, 3, 'library'),
  ('john-medley', 'W406', 'Meeting Room', 4, 'meeting'),
  ('john-medley', 'X453', 'Meeting Room', 4, 'meeting'),
  ('john-medley', 'X454', NULL, 4, 'study'),
  ('john-medley', 'E681', 'Meeting Room', 6, 'meeting'),
  ('john-medley', 'W604', 'Meeting Room', 6, 'meeting'),
  ('john-medley', 'W621A', 'Meeting Room', 6, 'meeting'),
  ('john-medley', 'W621B', 'Meeting Room', 6, 'meeting'),
  ('john-medley', 'W621C', 'Meeting Room', 6, 'meeting'),
  ('john-medley', 'W621D', 'Meeting Room', 6, 'meeting'),
  -- Kwong Lee Dow Building — UoM Building 263 — 49 rooms
  ('kwong-lee-dow', 'G06A', NULL, 0, 'study'),
  ('kwong-lee-dow', 'G08', NULL, 0, 'study'),
  ('kwong-lee-dow', 'G19', NULL, 0, 'study'),
  ('kwong-lee-dow', 'G22', NULL, 0, 'meeting'),
  ('kwong-lee-dow', 'G26', NULL, 0, 'study'),
  ('kwong-lee-dow', 'G27', NULL, 0, 'meeting'),
  ('kwong-lee-dow', 'G37', NULL, 0, 'meeting'),
  ('kwong-lee-dow', '103', NULL, 1, 'study'),
  ('kwong-lee-dow', '104', NULL, 1, 'study'),
  ('kwong-lee-dow', '105', NULL, 1, 'study'),
  ('kwong-lee-dow', '107', 'Student lounge with Microwave (107)', 1, 'study'),
  ('kwong-lee-dow', '108', NULL, 1, 'study'),
  ('kwong-lee-dow', '109', NULL, 1, 'study'),
  ('kwong-lee-dow', '201', NULL, 2, 'study'),
  ('kwong-lee-dow', '206', 'Low Sensory Room at Kwong Lee Dow', 2, 'library'),
  ('kwong-lee-dow', '209', NULL, 2, 'meeting'),
  ('kwong-lee-dow', '213', NULL, 2, 'tutorial'),
  ('kwong-lee-dow', '218', NULL, 2, 'tutorial'),
  ('kwong-lee-dow', '219', 'Flexible Learning Space', 2, 'lecture'),
  ('kwong-lee-dow', '227', 'Flexible Learning Space', 2, 'lecture'),
  ('kwong-lee-dow', '230', 'Q230 Theatre', 2, 'lecture'),
  ('kwong-lee-dow', '231', NULL, 2, 'tutorial'),
  ('kwong-lee-dow', '307', 'Meeting Room', 3, 'meeting'),
  ('kwong-lee-dow', '319', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '321', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '323', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '324', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '332', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '340', NULL, 3, 'study'),
  ('kwong-lee-dow', '341', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '342', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '343', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '350', 'Focus Room', 3, 'meeting'),
  ('kwong-lee-dow', '372', 'Meeting Room', 3, 'meeting'),
  ('kwong-lee-dow', '373', 'Meeting Room', 3, 'meeting'),
  ('kwong-lee-dow', '402', NULL, 4, 'lab'),
  ('kwong-lee-dow', '403', NULL, 4, 'lab'),
  ('kwong-lee-dow', '408', NULL, 4, 'lab'),
  ('kwong-lee-dow', '409', 'Collaborative Learning Space', 4, 'tutorial'),
  ('kwong-lee-dow', '416', 'Collaborative Learning Space', 4, 'tutorial'),
  ('kwong-lee-dow', '417', 'David Clarke Research Classroom', 4, 'tutorial'),
  ('kwong-lee-dow', '419', 'Collaborative Learning Space', 4, 'tutorial'),
  ('kwong-lee-dow', '420', 'Collaborative Learning Space', 4, 'tutorial'),
  ('kwong-lee-dow', '421', NULL, 4, 'tutorial'),
  ('kwong-lee-dow', '424B', NULL, 4, 'study'),
  ('kwong-lee-dow', '507', NULL, 5, 'tutorial'),
  ('kwong-lee-dow', '509', NULL, 5, 'tutorial'),
  ('kwong-lee-dow', '512', NULL, 5, 'study'),
  ('kwong-lee-dow', '515', NULL, 5, 'study'),
  -- Melbourne Law School — UoM Building 106 (LAW BUILDING) — 98 rooms
  ('law-school', 'G01', NULL, 0, 'tutorial'),
  ('law-school', 'G27', NULL, 0, 'tutorial'),
  ('law-school', 'G29', NULL, 0, 'tutorial'),
  ('law-school', 'G43', NULL, 0, 'study'),
  ('law-school', 'G44', NULL, 0, 'study'),
  ('law-school', 'G45', NULL, 0, 'study'),
  ('law-school', '0101', NULL, 1, 'study'),
  ('law-school', '0120', NULL, 1, 'study'),
  ('law-school', '0121', NULL, 1, 'study'),
  ('law-school', '0202', NULL, 2, 'tutorial'),
  ('law-school', '0203', NULL, 2, 'tutorial'),
  ('law-school', '0210', 'Meeting Room', 2, 'meeting'),
  ('law-school', '0213', 'Meeting Room', 2, 'meeting'),
  ('law-school', '0218', 'Meeting Room', 2, 'meeting'),
  ('law-school', '0221', NULL, 2, 'tutorial'),
  ('law-school', '0223', NULL, 2, 'tutorial'),
  ('law-school', '0224', NULL, 2, 'tutorial'),
  ('law-school', '0236', NULL, 2, 'study'),
  ('law-school', '0301', NULL, 3, 'study'),
  ('law-school', '0301A', NULL, 3, 'study'),
  ('law-school', '0301B', NULL, 3, 'study'),
  ('law-school', '0302', NULL, 3, 'library'),
  ('law-school', '0303', NULL, 3, 'library'),
  ('law-school', '0304', NULL, 3, 'library'),
  ('law-school', '0305', NULL, 3, 'library'),
  ('law-school', '0308', NULL, 3, 'library'),
  ('law-school', '0312', NULL, 3, 'meeting'),
  ('law-school', '0317', 'Flexible Learning Space', 3, 'lecture'),
  ('law-school', '0318', NULL, 3, 'study'),
  ('law-school', '0320', NULL, 3, 'library'),
  ('law-school', '0321', NULL, 3, 'library'),
  ('law-school', '0332', NULL, 3, 'meeting'),
  ('law-school', '0401', NULL, 4, 'study'),
  ('law-school', '0401A', NULL, 4, 'study'),
  ('law-school', '0401B', NULL, 4, 'library'),
  ('law-school', '0401D', NULL, 4, 'study'),
  ('law-school', '0402C', NULL, 4, 'library'),
  ('law-school', '0402D', NULL, 4, 'library'),
  ('law-school', '0402E', NULL, 4, 'study'),
  ('law-school', '0402F', NULL, 4, 'study'),
  ('law-school', '0402G', NULL, 4, 'study'),
  ('law-school', '0402H', NULL, 4, 'study'),
  ('law-school', '0420', NULL, 4, 'library'),
  ('law-school', '0426', NULL, 4, 'library'),
  ('law-school', '0426A', NULL, 4, 'library'),
  ('law-school', '0434', NULL, 4, 'library'),
  ('law-school', '0435', NULL, 4, 'library'),
  ('law-school', '0436', NULL, 4, 'library'),
  ('law-school', '0438', NULL, 4, 'library'),
  ('law-school', '0439', NULL, 4, 'library'),
  ('law-school', '0440', NULL, 4, 'study'),
  ('law-school', '0501A', NULL, 5, 'study'),
  ('law-school', '0501B', NULL, 5, 'study'),
  ('law-school', '0501C', NULL, 5, 'study'),
  ('law-school', '0501D', NULL, 5, 'study'),
  ('law-school', '0501E', NULL, 5, 'study'),
  ('law-school', '0501F', NULL, 5, 'library'),
  ('law-school', '0501G', NULL, 5, 'study'),
  ('law-school', '0501H', NULL, 5, 'library'),
  ('law-school', '0501I', NULL, 5, 'study'),
  ('law-school', '0504', NULL, 5, 'library'),
  ('law-school', '0505', NULL, 5, 'library'),
  ('law-school', '0506', NULL, 5, 'library'),
  ('law-school', '0507', NULL, 5, 'library'),
  ('law-school', '0521', NULL, 5, 'library'),
  ('law-school', '0522', NULL, 5, 'library'),
  ('law-school', '0523', NULL, 5, 'library'),
  ('law-school', '0524', NULL, 5, 'library'),
  ('law-school', '0527', NULL, 5, 'library'),
  ('law-school', '0528', NULL, 5, 'library'),
  ('law-school', '0530', 'PBL Space', 5, 'tutorial'),
  ('law-school', '0531', 'PBL Space', 5, 'tutorial'),
  ('law-school', '0532', 'PBL Space', 5, 'tutorial'),
  ('law-school', '0533', 'PBL Space', 5, 'tutorial'),
  ('law-school', '0535', NULL, 5, 'study'),
  ('law-school', '0536', NULL, 5, 'study'),
  ('law-school', '0537', NULL, 5, 'study'),
  ('law-school', '0605', NULL, 6, 'tutorial'),
  ('law-school', '0608', NULL, 6, 'tutorial'),
  ('law-school', '0609', NULL, 6, 'tutorial'),
  ('law-school', '0610', NULL, 6, 'tutorial'),
  ('law-school', '0611', NULL, 6, 'tutorial'),
  ('law-school', '0617', NULL, 6, 'library'),
  ('law-school', '0624A', 'Meeting Room', 6, 'meeting'),
  ('law-school', '0624B', 'Meeting Room', 6, 'meeting'),
  ('law-school', '0628', NULL, 6, 'tutorial'),
  ('law-school', '0629', NULL, 6, 'tutorial'),
  ('law-school', '0630', NULL, 6, 'tutorial'),
  ('law-school', '0722', 'Meeting Room', 7, 'meeting'),
  ('law-school', '0728A', NULL, 7, 'library'),
  ('law-school', '0828A', NULL, 8, 'library'),
  ('law-school', '0831', 'Meeting Room', 8, 'meeting'),
  ('law-school', '0903', 'Dean''s Meeting Room', 9, 'meeting'),
  ('law-school', '0905', 'Meeting Room', 9, 'meeting'),
  ('law-school', '0918', NULL, 9, 'library'),
  ('law-school', '0920', 'Flexible Learning Space', 9, 'lecture'),
  ('law-school', '0936', NULL, 9, 'library'),
  ('law-school', '1002', 'Law Boardroom', 10, 'meeting'),
  -- Melbourne School of Design — UoM Building 133 (GLYN DAVIS BUILDING) — 84 rooms
  ('melbourne-school-of-design', 'B115', NULL, -1, 'meeting'),
  ('melbourne-school-of-design', 'B120', 'The Singapore Theatre', -1, 'lecture'),
  ('melbourne-school-of-design', 'B121', 'The Malaysian Theatre', -1, 'lecture'),
  ('melbourne-school-of-design', 'B124', NULL, -1, 'meeting'),
  ('melbourne-school-of-design', 'B128', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B130', NULL, -1, 'study'),
  ('melbourne-school-of-design', 'B130A', NULL, -1, 'study'),
  ('melbourne-school-of-design', 'B131', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B133', 'Meeting Room', -1, 'meeting'),
  ('melbourne-school-of-design', 'B134', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B135', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B136', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B137', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B138', NULL, -1, 'library'),
  ('melbourne-school-of-design', 'B138A', NULL, -1, 'study'),
  ('melbourne-school-of-design', 'B138B', NULL, -1, 'study'),
  ('melbourne-school-of-design', 'G02', NULL, 0, 'tutorial'),
  ('melbourne-school-of-design', 'G29', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G30', 'G30 ABP Library', 0, 'library'),
  ('melbourne-school-of-design', 'G32', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G32A', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G33', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G34', NULL, 0, 'library'),
  ('melbourne-school-of-design', 'G34A', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G35', NULL, 0, 'library'),
  ('melbourne-school-of-design', 'G36', NULL, 0, 'library'),
  ('melbourne-school-of-design', 'G37', NULL, 0, 'study'),
  ('melbourne-school-of-design', 'G38', NULL, 0, 'meeting'),
  ('melbourne-school-of-design', 'G44', NULL, 0, 'study'),
  ('melbourne-school-of-design', '102', 'Dean''s Conference Room', 1, 'meeting'),
  ('melbourne-school-of-design', '109', 'Meeting Room', 1, 'meeting'),
  ('melbourne-school-of-design', '117', 'Design Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '118', 'Design Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '124', 'Design Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '125', 'Douglas & Joaquina Lee Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '137', 'Design Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '138', 'Evan Walker Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '139', 'George Tibbits Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '140', 'Ellison Harvey Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '141', 'CAD Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '142', 'CAD Studio', 1, 'tutorial'),
  ('melbourne-school-of-design', '144', NULL, 1, 'tutorial'),
  ('melbourne-school-of-design', '146', NULL, 1, 'tutorial'),
  ('melbourne-school-of-design', '201', NULL, 2, 'meeting'),
  ('melbourne-school-of-design', '202', NULL, 2, 'meeting'),
  ('melbourne-school-of-design', '207A', NULL, 2, 'study'),
  ('melbourne-school-of-design', '213', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '215', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '216', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '226', 'Hansen Yuncken Studio 2', 2, 'tutorial'),
  ('melbourne-school-of-design', '227', 'Hong Kong Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '228', 'Sarawak Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '229', 'Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '230', NULL, 2, 'study'),
  ('melbourne-school-of-design', '236', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '237', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '238', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '239', '1970''s Alumni Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '240', '1960''s Alumni Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '241', 'Design Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '242', NULL, 2, 'study'),
  ('melbourne-school-of-design', '244', 'CAD Teaching Studio', 2, 'tutorial'),
  ('melbourne-school-of-design', '247', NULL, 2, 'study'),
  ('melbourne-school-of-design', '302', 'Meeting Room', 3, 'meeting'),
  ('melbourne-school-of-design', '308', 'Meeting Room', 3, 'meeting'),
  ('melbourne-school-of-design', '314', 'Hansen Yuncken Studio 3', 3, 'tutorial'),
  ('melbourne-school-of-design', '318', NULL, 3, 'meeting'),
  ('melbourne-school-of-design', '319', NULL, 3, 'study'),
  ('melbourne-school-of-design', '319A', NULL, 3, 'study'),
  ('melbourne-school-of-design', '325', NULL, 3, 'meeting'),
  ('melbourne-school-of-design', '335', NULL, 3, 'study'),
  ('melbourne-school-of-design', '336', NULL, 3, 'meeting'),
  ('melbourne-school-of-design', '341', NULL, 3, 'meeting'),
  ('melbourne-school-of-design', '358', NULL, 3, 'library'),
  ('melbourne-school-of-design', '359', NULL, 3, 'meeting'),
  ('melbourne-school-of-design', '401', NULL, 4, 'meeting'),
  ('melbourne-school-of-design', '408', 'Hansen Yuncken Studio 4', 4, 'tutorial'),
  ('melbourne-school-of-design', '412', NULL, 4, 'meeting'),
  ('melbourne-school-of-design', '413A', NULL, 4, 'study'),
  ('melbourne-school-of-design', '419', NULL, 4, 'meeting'),
  ('melbourne-school-of-design', '430', NULL, 4, 'meeting'),
  ('melbourne-school-of-design', '435', NULL, 4, 'meeting'),
  ('melbourne-school-of-design', '448', 'Design Studio', 4, 'tutorial'),
  ('melbourne-school-of-design', '449', 'Design Studio', 4, 'tutorial'),
  -- Old Arts Building — UoM Building 149 — 36 rooms
  ('old-arts', '103', NULL, 1, 'tutorial'),
  ('old-arts', '116', 'Collaborative Learning Space', 1, 'tutorial'),
  ('old-arts', '124', 'Flexible Learning Space', 1, 'tutorial'),
  ('old-arts', '129', 'Flexible Learning Space', 1, 'tutorial'),
  ('old-arts', '141', NULL, 1, 'meeting'),
  ('old-arts', '143', 'Collaborative Learning Space', 1, 'tutorial'),
  ('old-arts', '152', NULL, 1, 'tutorial'),
  ('old-arts', '155', 'Flexible Learning Space', 1, 'lecture'),
  ('old-arts', '156', 'Collaborative Learning Space', 1, 'tutorial'),
  ('old-arts', '163', NULL, 1, 'meeting'),
  ('old-arts', '204', 'Flexible Learning Space', 2, 'lecture'),
  ('old-arts', '205', 'Collaborative Learning Space', 2, 'tutorial'),
  ('old-arts', '207A', NULL, 2, 'study'),
  ('old-arts', '209', 'Collaborative Learning Space', 2, 'tutorial'),
  ('old-arts', '210', 'Collaborative Learning Space', 2, 'tutorial'),
  ('old-arts', '210A', NULL, 2, 'study'),
  ('old-arts', '213', 'Atrium Meeting Room', 2, 'meeting'),
  ('old-arts', '219', NULL, 2, 'meeting'),
  ('old-arts', '220', NULL, 2, 'meeting'),
  ('old-arts', '227', 'Cecil Scutt Room', 2, 'tutorial'),
  ('old-arts', '231', 'Video Conference', 2, 'meeting'),
  ('old-arts', '246', NULL, 2, 'meeting'),
  ('old-arts', '254', NULL, 2, 'tutorial'),
  ('old-arts', '257', 'Collaborative Learning Space 2', 2, 'tutorial'),
  ('old-arts', '263', 'Collaborative Learning Space 1', 2, 'tutorial'),
  ('old-arts', 'C201', NULL, 2, 'study'),
  ('old-arts', 'C202', NULL, 2, 'study'),
  ('old-arts', 'C203', NULL, 2, 'study'),
  ('old-arts', 'C204', NULL, 2, 'study'),
  ('old-arts', 'C206', NULL, 2, 'study'),
  ('old-arts', 'C207', NULL, 2, 'study'),
  ('old-arts', 'C208', NULL, 2, 'study'),
  ('old-arts', 'C209', NULL, 2, 'study'),
  ('old-arts', 'C210', NULL, 2, 'study'),
  ('old-arts', 'C211', NULL, 2, 'study'),
  ('old-arts', 'C212', NULL, 2, 'study'),
  -- Peter Hall Building — UoM Building 160 — 9 rooms
  ('peter-hall', 'G01', 'JH MICHELL THEATRE (G01)', 0, 'lecture'),
  ('peter-hall', 'G06', NULL, 0, 'study'),
  ('peter-hall', 'G38', 'Meeting Room', 0, 'meeting'),
  ('peter-hall', 'G39', 'Thomas Cherry Room (G39)', 0, 'meeting'),
  ('peter-hall', 'G50A', 'Math Assist', 0, 'tutorial'),
  ('peter-hall', '101', 'Maurice Belz Room', 1, 'meeting'),
  ('peter-hall', '107', NULL, 1, 'tutorial'),
  ('peter-hall', '213', NULL, 2, 'tutorial'),
  ('peter-hall', '215', NULL, 2, 'tutorial'),
  -- Redmond Barry Building — UoM Building 115 — 30 rooms
  ('redmond-barry', '101', 'LYLE THEATRE (101)', 1, 'lecture'),
  ('redmond-barry', '102', 'LATHAM THEATRE (102)', 1, 'lecture'),
  ('redmond-barry', '103', 'LOWE THEATRE (103)', 1, 'lecture'),
  ('redmond-barry', '104', NULL, 1, 'lecture'),
  ('redmond-barry', '304', NULL, 3, 'tutorial'),
  ('redmond-barry', '305', NULL, 3, 'tutorial'),
  ('redmond-barry', '406', NULL, 4, 'study'),
  ('redmond-barry', '412', NULL, 4, 'tutorial'),
  ('redmond-barry', '416', NULL, 4, 'lab'),
  ('redmond-barry', '417A', NULL, 4, 'lab'),
  ('redmond-barry', '417B', NULL, 4, 'lab'),
  ('redmond-barry', '419', 'Ethics & Well-Being Hub Meeting Rm', 4, 'meeting'),
  ('redmond-barry', '508', NULL, 5, 'tutorial'),
  ('redmond-barry', '513', NULL, 5, 'tutorial'),
  ('redmond-barry', '516', NULL, 5, 'tutorial'),
  ('redmond-barry', '615', NULL, 6, 'tutorial'),
  ('redmond-barry', '616', NULL, 6, 'tutorial'),
  ('redmond-barry', '718', 'Collaborative Learning Space', 7, 'tutorial'),
  ('redmond-barry', '719', 'Collaborative Learning Space', 7, 'tutorial'),
  ('redmond-barry', '822', NULL, 8, 'tutorial'),
  ('redmond-barry', '1004', NULL, 10, 'tutorial'),
  ('redmond-barry', '1005', NULL, 10, 'tutorial'),
  ('redmond-barry', '1006', NULL, 10, 'tutorial'),
  ('redmond-barry', '1007', NULL, 10, 'tutorial'),
  ('redmond-barry', '1011', NULL, 10, 'study'),
  ('redmond-barry', '1012', NULL, 10, 'study'),
  ('redmond-barry', '1101', 'PPP Lab', 11, 'meeting'),
  ('redmond-barry', '1120', NULL, 11, 'tutorial'),
  ('redmond-barry', '1123', NULL, 11, 'tutorial'),
  ('redmond-barry', '1206', 'Lvl 12 Conference Room', 12, 'meeting'),
  -- Student Pavilion — UoM Building 162 — 21 rooms
  ('student-pavilion', '201', NULL, 2, 'study'),
  ('student-pavilion', '202', NULL, 2, 'study'),
  ('student-pavilion', '205', NULL, 2, 'meeting'),
  ('student-pavilion', '206', NULL, 2, 'meeting'),
  ('student-pavilion', '208', NULL, 2, 'study'),
  ('student-pavilion', '212', NULL, 2, 'library'),
  ('student-pavilion', '214', NULL, 2, 'study'),
  ('student-pavilion', '215', NULL, 2, 'study'),
  ('student-pavilion', '219', NULL, 2, 'library'),
  ('student-pavilion', '301', NULL, 3, 'study'),
  ('student-pavilion', '302', NULL, 3, 'study'),
  ('student-pavilion', '303', NULL, 3, 'study'),
  ('student-pavilion', '305', NULL, 3, 'library'),
  ('student-pavilion', '306', NULL, 3, 'library'),
  ('student-pavilion', '308', NULL, 3, 'study'),
  ('student-pavilion', '311', NULL, 3, 'library'),
  ('student-pavilion', '312', NULL, 3, 'library'),
  ('student-pavilion', '313', NULL, 3, 'library'),
  ('student-pavilion', '314', NULL, 3, 'library'),
  ('student-pavilion', '315', NULL, 3, 'library'),
  ('student-pavilion', '317', NULL, 3, 'library'),
  -- The Spot — UoM Building 110 — 69 rooms
  ('the-spot', 'CG01A', NULL, 0, 'study'),
  ('the-spot', 'CG01B', NULL, 0, 'study'),
  ('the-spot', '1007', NULL, 1, 'study'),
  ('the-spot', '1009', NULL, 1, 'study'),
  ('the-spot', '1011', NULL, 1, 'study'),
  ('the-spot', '1012', NULL, 1, 'study'),
  ('the-spot', '1015', NULL, 1, 'study'),
  ('the-spot', '2001', 'Collaborative Learning Space (2001)', 2, 'tutorial'),
  ('the-spot', '2002', 'Collaborative Learning Space (2002)', 2, 'tutorial'),
  ('the-spot', '2013', NULL, 2, 'tutorial'),
  ('the-spot', '2014', NULL, 2, 'tutorial'),
  ('the-spot', '2015', NULL, 2, 'tutorial'),
  ('the-spot', '2016', NULL, 2, 'tutorial'),
  ('the-spot', '2017', NULL, 2, 'tutorial'),
  ('the-spot', '2018', NULL, 2, 'tutorial'),
  ('the-spot', '2019', NULL, 2, 'tutorial'),
  ('the-spot', '2020', NULL, 2, 'tutorial'),
  ('the-spot', '2021', NULL, 2, 'study'),
  ('the-spot', '2021A', NULL, 2, 'study'),
  ('the-spot', '2021B', NULL, 2, 'study'),
  ('the-spot', '2021C', NULL, 2, 'study'),
  ('the-spot', '2021D', NULL, 2, 'study'),
  ('the-spot', '2021E', NULL, 2, 'study'),
  ('the-spot', '3008', 'Theatrette (3008)', 3, 'lecture'),
  ('the-spot', '3012', NULL, 3, 'tutorial'),
  ('the-spot', '3013', NULL, 3, 'tutorial'),
  ('the-spot', '3016', NULL, 3, 'study'),
  ('the-spot', '3016A', NULL, 3, 'study'),
  ('the-spot', '3016B', NULL, 3, 'study'),
  ('the-spot', '3016C', NULL, 3, 'study'),
  ('the-spot', '3016D', NULL, 3, 'study'),
  ('the-spot', '3016E', NULL, 3, 'study'),
  ('the-spot', '3032', NULL, 3, 'tutorial'),
  ('the-spot', '3033', NULL, 3, 'tutorial'),
  ('the-spot', '4007', 'Lecture Theatrette', 4, 'lecture'),
  ('the-spot', '5007', 'Lecture Theatrette (5007)', 5, 'lecture'),
  ('the-spot', '5008', 'Lecture Theatrette (5008)', 5, 'lecture'),
  ('the-spot', '5013', 'Collaborative Learning Space (5013)', 5, 'tutorial'),
  ('the-spot', '5014', 'Collaborative Learning Space (5014)', 5, 'tutorial'),
  ('the-spot', '5015', NULL, 5, 'tutorial'),
  ('the-spot', '5018', NULL, 5, 'tutorial'),
  ('the-spot', '5019', NULL, 5, 'tutorial'),
  ('the-spot', '6002', 'Meeting Room (6002)', 6, 'meeting'),
  ('the-spot', '6003', 'Meeting Room (6003)', 6, 'meeting'),
  ('the-spot', '6014', 'Collaborative Learning Space (6014)', 6, 'tutorial'),
  ('the-spot', '6015', 'Collaborative Learning Space (6015)', 6, 'tutorial'),
  ('the-spot', '6017', NULL, 6, 'study'),
  ('the-spot', '6017A', NULL, 6, 'study'),
  ('the-spot', '6017B', NULL, 6, 'study'),
  ('the-spot', '6017C', NULL, 6, 'study'),
  ('the-spot', '6017D', NULL, 6, 'study'),
  ('the-spot', '6017E', NULL, 6, 'study'),
  ('the-spot', '7013', 'Meeting Room', 7, 'meeting'),
  ('the-spot', '7029', 'Meeting Room (7029)', 7, 'meeting'),
  ('the-spot', '7039', 'The Fish Bowl (7039)', 7, 'meeting'),
  ('the-spot', '8013', 'Meeting Room (8013)', 8, 'meeting'),
  ('the-spot', '8038', 'Meeting Room (8038)', 8, 'meeting'),
  ('the-spot', '9013', 'Meeting Room', 9, 'meeting'),
  ('the-spot', '9037', NULL, 9, 'tutorial'),
  ('the-spot', '10013', 'Meeting room', 10, 'meeting'),
  ('the-spot', '10039', NULL, 10, 'tutorial'),
  ('the-spot', '11013', 'Meeting Room', 11, 'meeting'),
  ('the-spot', '11038', NULL, 11, 'tutorial'),
  ('the-spot', '12013', 'Meeting Room', 12, 'meeting'),
  ('the-spot', '12020', 'Dean''s Boardroom', 12, 'meeting'),
  ('the-spot', '12028', 'Meeting Room', 12, 'meeting'),
  ('the-spot', '12029', 'Meeting Room', 12, 'meeting'),
  ('the-spot', '12032A', 'Meeting Room', 12, 'meeting'),
  ('the-spot', '12032B', 'Meeting Room', 12, 'meeting')
) AS v(slug, code, name, floor_level, room_type)
JOIN buildings b ON b.slug = v.slug
ON CONFLICT (building_id, code) DO UPDATE SET
  name        = EXCLUDED.name,
  floor_level = EXCLUDED.floor_level,
  room_type   = EXCLUDED.room_type;
